name: isac
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - nvidia
  - pypi
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - _libgcc_mutex
  - _openmp_mutex
  - blas
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - charset-normalizer
  - contourpy
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-opencl
  - cuda-runtime
  - cuda-version
  - cycler
  - ffmpeg
  - filelock
  - fonttools
  - freetype
  - fsspec
  - giflib
  - gmp
  - gmpy2
  - gnutls
  - idna
  - intel-openmp
  - jinja2
  - jpeg
  - kiwisolver
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcusolver
  - libcusparse
  - libdeflate
  - libffi
  - libgcc-ng
  - libgomp
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libnpp
  - libnvjitlink
  - libnvjpeg
  - libpng=
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libwebp-base
  - libwebp
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - mkl-service
  - mkl
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - ncurses
  - nettle
  - networkx
  - numpy-base
  - numpy
  - ocl-icd
  - openh264
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pillow
  - pyparsing
  - pysocks
  - python-dateutil
  - pytorch-cuda
  - pytorch-mutex
  - pytorch
  - pytz
  - pyyaml
  - readline
  - requests
  - safetensors
  - scipy
  - setuptools
  - six
  - sqlite
  - sympy
  - tbb
  - timm
  - tk
  - torchaudio
  - torchtriton
  - torchvision
  - tqdm
  - typing_extensions
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
